### ISSUE TITLE
Dependency "YNSearch" has no shared framework schemes

### ISSUE THREAD

**Issue by neha275** [younatics/YNSearch#1]
I try to install the library through the Carthage, it's giving me below error

*** Fetching YNSearch
*** Checking out YNSearch at "0.2.1"
*** xcodebuild output can be found in /var/folders/lf/13b1q2vd1892s9l8knv_m7nw0000gn/T/carthage-xcodebuild.VmVLpH.log
*** Skipped building YNSearch due to the error:
Dependency "YNSearch" has no shared framework schemes

**Comment by younatics** [comment]
Hello @neha275 , 
I googled and I find [Issue](]https://github.com/Carthage/Carthage/issues/387) in Carthage. 
Could you give me more information like xcodebuild log? Thanks!

**Comment by neha275** [comment]
Hello @younatics ,
The log is empty.

I try again to Carthage still the same issue, when I open the log file it is empty

**Comment by younatics** [comment]
Hello @neha275,
I found what happened in this project. I will change this project ASAP

**Comment by younatics** [comment]
Oops my mistake I will close this issue when it is done

**Comment by younatics** [comment]
Could you try again with [v0.3.0](https://github.com/younatics/YNSearch/releases/tag/0.3.0) ?
Thanks, younatics

**Comment by neha275** [comment]
yes it working now

**Comment by younatics** [comment]
Great! I will close this issue :)
