### ISSUE TITLE
How to show Navigationbar?

### ISSUE THREAD

**Issue by MHX792** [younatics/YNSearch#10]
Hi,
I would rather like to have a navigationcontroller instead of a modal view for clicked items.
How to make the navigationbar visible?

Thanks and kind regards

Edit:
I found out that `self.navigationController!.isNavigationBarHidden = false` does the job, but then the textfield is hidden. How to put the textfield in front of the navigation bar?

**Comment by SolitaryWolf** [comment]
Found by myself. update self.ynSearchTextfieldView = YNSearchTextFieldView(frame: CGRect(x: 20, y: 60, width: width-40, height: 50)) and self.ynSearchView = YNSearchView(frame: CGRect(x: 0, y: 110, width: width, height: height-70))

**Comment by younatics** [comment]
Thanks!
