### ISSUE TITLE
Easy way to customise cells?

### ISSUE THREAD

**Issue by spinach** [younatics/YNSearch#3]
Great project, thank you for sharing!

I am curious if there is an easy way to be able to customise the look and feel of our cells, for example the result cells in `YNSearchListViewCell`. 

Also, if I want to add an additional field, such as a `UILabel` on the right of the cell (for example specifying the occurence of a particular item), is there an easy way to do that in your library?

Thanks again!

**Comment by younatics** [comment]
Hello @spinach,
I am developing additional works what you want right now.
I will tell you if it is done.
Cheers!

**Comment by spinach** [comment]
Awesome thank you for your work!

**Comment by younatics** [comment]
Hello @spinach,
I made ` func ynSearchListViewClicked(object: YNSearchModel)` to get object. It will be useful when you make customize cell.
Actually, you have to override `YNSearchListView` with your self :( 
Cheers!

**Comment by younatics** [comment]
Wait, I will make it. I need it...! 
Thanks,

**Comment by spinach** [comment]
Thanks @younatics ! Looking forward for more customisation options such as custom search matching algorithm :)

**Comment by younatics** [comment]
Hello @spinach, 
I major updated 2.0.0 for you :)
I also tried to use custom cell. and it worked! 
Also, I use [Objectification](https://github.com/younatics/Objectification) for search algorithm.
Please see and give it a star!

Cheers!

**Comment by spinach** [comment]
Awesome, thanks for the great work. Will check it out later in the day. And ofc, I already ⭐️ it!!
