### ISSUE TITLE
DemoSearchHistories only gets set after first search

### ISSUE THREAD

**Issue by edgeofchaos2005** [younatics/YNSearch#4]
Hi,

Firstly, great repo - its perfect for what I'm wanting to do!

Secondly, I can't seem to get the demoSearchHistories array to appear on the initial load of the app - I can only get it to appear once I tap the search text field, then click cancel.

I've tried putting the "ynSearch.setSearchHistories(value: demoSearchHistories)" into a viewDidAppear() class, but no luck. It appears to be the same issue with the demo repo as well.

Thanks!

**Comment by edgeofchaos2005** [comment]
Just playing about a bit more, I was able to render the demoSearchHistories by calling the redrawSearchHistoryButton() that was being called on the cancel button of the search field, as below:
```
override func viewDidAppear(_ animated: Bool) {
    self.ynSearchView.ynSearchMainView.redrawSearchHistoryButtons()
}

**Comment by younatics** [comment]
Great!
