### ISSUE TITLE
Clear history button and x button doesn't work if there are a lot of histories

### ISSUE THREAD

**Issue by Ahmedshubber** [younatics/YNSearch#5]
@younatics @controversial The clear history button only works if there are a few histories in the scroll view to the point where it fits inside the current view and the history table/scroll view does scroll. But once the tableview has enough histories to the point where the clear history button is not in the view then the clear history button doesn't work for some reason. Also the "x" button right beside each history doesn't work for same reason. If there are a little bit of history cells then the buttons work fine, but if there a lot then both buttons are disabled or don't work. Try it for yourself. Create a bunch of histories, probably 15-20 searches so you have 15-20 history cells and the buttons inside the history cell and clear history button wont work. Can you fix this as soon as possible. Im trying to roll out my app.

**Comment by younatics** [comment]
Hello @Ahmedshubber , I will see and change it ASAP and notify you again.
Thanks

**Comment by younatics** [comment]
@Ahmedshubber  Please see [v2.3.0](https://github.com/younatics/YNSearch/releases/tag/2.3.0)
Thanks.
